project_id = "kpsilbmmedonhxjofixm"

[functions.create-agent]
verify_jwt = false

[functions.update-agent]
verify_jwt = false

[functions.delete-agent]
verify_jwt = false

[functions.launch-call]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.campaign-scheduler]
verify_jwt = false

[functions.provision-phone-number]
verify_jwt = false

[functions.upload-document]
verify_jwt = false
